project_id = "xciubsogktecqcgafwaa"

[functions.receive-actions]
verify_jwt = false

[functions.postgres-api]
verify_jwt = false

[functions.test-postgres]
verify_jwt = false

[functions.receive-content-ideas]
verify_jwt = false

[functions.upload-image]
verify_jwt = false